const db = [
    {
        id: 0,
        popular: 'Популярное',
        img: 'https://i.ibb.co/CVDsfyX/ariel.png',
        weight: '15X28.8 г',
        title: 'ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'AOS',
        price: '48,76 ₸',
    },
    {
        id: 1,
        popular: 'Популярное',
        img: 'https://i.ibb.co/y6t7tR1/bimax.png',
        weight: '1500 г',
        title: 'BIMAX Порошок стиральный Автомат 100 пятен COMPACT',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'AOS', 
        price: '48,76 ₸',
    },
    {
        id:2,
        popular: 'Популярное',
        img: 'https://i.ibb.co/1X0KNYm/aos.png',
        weight: '450мл',
        title: 'AOS средство для мытья посуды Crystal',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'AOS',
        price: '48,76 ₸',
    },
    {
        id: 3,
        popular: 'Популярное',
        img: 'https://i.ibb.co/d7WNJF5/sorti.png',
        weight: '450мл',
        title: 'AOS Ср-во для мытья посуды Апельсин+мята',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'AOS',
        price: '48,76 ₸ ',
    },
    {
        id: 4,
        popular: 'Популярное',
        img: 'https://i.ibb.co/CVDsfyX/ariel.png',
        weight: '15X28.8 г',
        title: 'ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'AOS',
        price: '48,76 ₸',
    },
    {
        id: 5,
        popular: 'Популярное',
        img: 'https://i.ibb.co/y6t7tR1/bimax.png',
        weight: '1500 г',
        title: 'BIMAX Порошок стиральный Автомат 100 пятен COMPACT',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'AOS',
        price: '48,76 ₸',
    },
    {
        id: 6,
        popular: 'Популярное',
        img: 'https://i.ibb.co/1X0KNYm/aos.png',
        weight: '450мл',
        title: 'AOS средство для мытья посуды Crystal',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'Бренд:AOS',
        price: '48,76 ₸',
    },
    {
        id: 7,
        popular: 'Популярное',
        img: 'https://i.ibb.co/d7WNJF5/sorti.png',
        weight: '450мл',
        title: 'AOS Ср-во для мытья посуды Апельсин+мята',
        barcode:'4604049097548',
        mark:'Нэфис',
        brand:'AOS',
        price: '48,76 ₸',
    },
];
export default db